thelokeshgoel00/Competitive_Programming

Hackerrank/Anagram.cpp
Hackerrank/bigSorting.c

https://www.hackerrank.com/challenges/big-sorting/problem

Big Sorting

---

Interviewbit/Rotated Array
README.md

merge to add a new folder for Interviewbit question

add Interviewbit folder and a question's solution

---

Hackerrank/Encryption.c

https://www.hackerrank.com/challenges/encryption/problem

Encryption Hackerrank

---

GeeksForGeeks/ContainerWithMostWater.cpp
GeeksForGeeks/DeleteMiddleElement.cpp

(https://practice.geeksforgeeks.org/problems/container-with-most-water/0)

Container with most water.cpp

---

Hackerrank/numberLineJumps.c

https://www.hackerrank.com/challenges/kangaroo/problem

Number Line Jump

---

Hackerrank/MigratoryBirds.c

https://www.hackerrank.com/challenges/migratory-birds/problem

Migratory Birds

---

Hackerrank/BeautifulTriplets.c
Hackerrank/saveThePrisoner.c

https://www.hackerrank.com/challenges/beautiful-triplets/problem

Beautiful triplets

---

Hackerrank/saveThePrisoner.c

https://www.hackerrank.com/challenges/save-the-prisoner/problem

Save The Prisoner

---

LeetCode/Intersection of two linked llist.cpp
LeetCode/reverse words in a string.cpp

This reverts commit e08228b279f3f580b8abcb2898c59d5dcb4c4b07.

reverse words in string.cpp

---

Interviewbit/DynamicProgramming/Intersecting Chords in a Circle
Interviewbit/DynamicProgramming/Jump Game Array
Interviewbit/DynamicProgramming/Largest area of rectangle with permutations
Interviewbit/DynamicProgramming/Length of Longest Subsequence
Interviewbit/DynamicProgramming/Longest Arithmetic Progression
Interviewbit/DynamicProgramming/Max Sum Without Adjacent Elements
Interviewbit/DynamicProgramming/Min jumps array
Interviewbit/DynamicProgramming/N digit numbers with digit sum S
Interviewbit/DynamicProgramming/Stairs
Interviewbit/DynamicProgramming/Ways to decode
Interviewbit/Math/Excel Coloumn Title
Interviewbit/Math/Excel Column Number
Interviewbit/Math/FizzBuzz
Interviewbit/Math/Greatest Common Divisor
Interviewbit/Math/Grid Unique Paths
Interviewbit/Math/Largest Coprime Divisor
Interviewbit/Math/Palindrome Integer
Interviewbit/Math/Power of two integers
Interviewbit/Math/Prime Sum
Interviewbit/Math/Rearrange array
Interviewbit/Math/Reverse Integer
Interviewbit/Math/Sum of pairwise hamming distance
Interviewbit/Math/Trailing Zeroes in Factorial

Added Math problem programs in interviewbit

Interviewbit math

---

Interviewbit/DynamicProgramming/Intersecting Chords in a Circle
Interviewbit/DynamicProgramming/Jump Game Array
Interviewbit/DynamicProgramming/Largest area of rectangle with permutations
Interviewbit/DynamicProgramming/Length of Longest Subsequence
Interviewbit/DynamicProgramming/Longest Arithmetic Progression
Interviewbit/DynamicProgramming/Max Sum Without Adjacent Elements
Interviewbit/DynamicProgramming/Min jumps array
Interviewbit/DynamicProgramming/N digit numbers with digit sum S
Interviewbit/DynamicProgramming/Stairs
Interviewbit/DynamicProgramming/Ways to decode

Added dynamic programming programs in interviewbit

added DP solutions

---

Hackerrank/UtopianTree.c

https://www.hackerrank.com/challenges/utopian-tree/problem

Utopian Tree

---

Hackerrank/CircularArrayRotation.c
Hackerrank/SherlockAndSquares.c
Hackerrank/UtopianTree.c

https://www.hackerrank.com/challenges/circular-array-rotation/problem

Circular array

---

Hackerrank/CircularArrayRotation.c
Hackerrank/CutTheSticks.c
Hackerrank/SherlockAndSquares.c
Hackerrank/UtopianTree.c

https://www.hackerrank.com/challenges/cut-the-sticks/problem

Cut the sticks

---

Hackerrank/Python/Basic Data Types/findTheSecondLargestNumber.py
Hackerrank/Python/Basic Data Types/findingThePercentage.py
Hackerrank/Python/Basic Data Types/listComprehensions.py
Hackerrank/Python/Basic Data Types/lists.py
Hackerrank/Python/Basic Data Types/nestedList.py
Hackerrank/Python/Basic Data Types/tuples.py

https://www.hackerrank.com/domains/python?filters%5Bsubdomains%5D%5B%5D=py-basic-data-types

HackerRank Python Problems -- Basic Data Types 

---

Kattis/cheatingbooleantree.c

[Problem Prompt](https://open.kattis.com/problems/cheatingbooleantree)
Passes all known test cases and three hidden ones.

Add `Cheating A Boolean Tree` Kattis `C` solution

---

Hackerrank/binaryTreeHeight.cpp

Added code for Height of binary Tree

Height of binary tree

---

LeetCode/maximum_number_of_achievable_transfer_requests.py

A hard problem with brute force solution due to lower constraints

Adding solution for problem 1601 - hacktoberfest

---

LeetCode/first_missing_positive.py

@thelokeshgoel00 can you help me on adding label **hacktoberfest** to my existing PRs?

Adding solution for problem 41 in python - hacktoberfest

---

Hackerrank/Python/Basic Data Types/compressString.py

Added Code for Compress the string

Added Code for Compress the string

---

CodeForces/CF1420A.py

Cube Sorting code using python , Held on [Code forces](https://codeforces.com/contest/1420/problems)

CubeSorting using python (https://codeforces.com/contest/1420/problems)

---

.vscode/c_cpp_properties.json
ProjectEuler/1.cpp
ProjectEuler/10.cpp
ProjectEuler/2.cpp
ProjectEuler/3.cpp
ProjectEuler/4.cpp
ProjectEuler/5.cpp
ProjectEuler/6.cpp
ProjectEuler/7.cpp
ProjectEuler/8.cpp
ProjectEuler/9.cpp

10 problems are solved from project euler

New folder for projevt euler has been created and its  10 problems are solved

---

LeetCode/Jump_game.py

added a python solution for leetcode problem #55 called Jump game.

added solution for leetcode prblm #55

---

ProjectEuler/11.cpp
ProjectEuler/12.cpp
ProjectEuler/13.cpp
ProjectEuler/14.cpp
ProjectEuler/15.cpp
ProjectEuler/16.cpp
ProjectEuler/17.cpp
ProjectEuler/18.cpp
ProjectEuler/19.cpp
ProjectEuler/20.cpp

i have added solutions for 11 -12 of Project euler

Solutions from 11-20 are added

---

LeetCode/Delete node in Linked list.cpp

Added Delete node in a Linked list.cpp

Hactoberfest

---

Miscellaneous/Merge Linked Lists

Added in miscellanious folder.

Merge Two Linked Lists using new nodes-hacktoberfest

---

Interviewbit/Arrays/Add_One_To_Number.py
Interviewbit/Arrays/Find_Duplicate_in_Array.py
Interviewbit/Arrays/Flip.cpp
Interviewbit/Arrays/Hotel_Bookings_Possible.cpp
Interviewbit/Arrays/Max_Distance.cpp
Interviewbit/Arrays/Max_Sum_Contiguous_Subarray.py
Interviewbit/Arrays/Maximum_Absolute_Difference.py
Interviewbit/Arrays/Maximum_Consecutive_Gap.py
Interviewbit/Arrays/Maximum_Unsorted_Subarray.cpp
Interviewbit/Arrays/Min_Steps_in_Infinite_Grid.cpp
Interviewbit/Arrays/Noble_Integer.cpp
Interviewbit/Arrays/Triplets_with_Sum_between_given_range.cpp
Interviewbit/Arrays/Wave_Array.cpp

I've added some Arrays questions to the code base. Kindly review and merge this PR for hacktoberfest.
TIA!

Added some arrays questions

---

CodeChef/CHEFCAKE.cpp
Hackerrank/1D_Arrays.c
Hackerrank/ArrayReversal.c

ArrayReversal

---

LeetCode/Valid_paranthesis.py

added solution for leetcode problem #20 valid paranthesis.

added solution for leetcode prblm #20

---

Interviewbit/Arrays/Anti_Diagonals.cpp
Interviewbit/Arrays/Find_Permutation.cpp
Interviewbit/Arrays/Kth_Row_of_Pascals_Triangle.cpp
Interviewbit/Arrays/Largest_Number.py
Interviewbit/Arrays/Next_Permutation.cpp
Interviewbit/Arrays/Pascal_Triangle.cpp
Interviewbit/Arrays/Spiral_Order_Matrix_II.cpp

Kindly review and merge. Thanks for your feedback on the previous contribution!

Adding 7 more Arrays questions to the list

---

Hackerrank/Append and delete

Create Append and delete

---

Hackerrank/recursion.java

https://www.hackerrank.com/challenges/30-recursion/problem

Adding recursion problem solution- Hacktoberfest
